; The boomerangs thrown by the boss at level #2

TBL_BOOMERANG_1: EQU 0xE2FB
TBL_BOOMERANG_2: EQU 0xE30B

; Entry 0
; bit #4: boomerang active
; bit #5: boomerang damaged Thomas
; bit #6: boomerang active
BOOMERANG_PROPS_IDX: EQU 0

BOOMERANG_ACTIVE1_BIT: EQU 4
BOOMERANG_CAUSED_DAMAGE_BIT: EQU 5
BOOMERANG_ACTIVE2_BIT: EQU 6

; Entry 1: direction of the boomerang
BOOMERANG_DIRECTION: EQU 1
;
;BOOMERANG_DIRECTION_LEFT: EQU 0
BOOMERANG_DIRECTION_TURNING: EQU 1
;BOOMERANG_DIRECTION_RIGHT: EQU 2



