; Magical elements, mainly at the beginning of level #2

; SEGUIR: index all E36... with MAGICAL_ELEMENTS_CONFIG
MAGICAL_ELEMENTS_CONFIG: EQU 0xE360 ; length 24 (0xE360, ..., 0xE377), magical elements
; Copied using INDICES_DATA_MAGICAL_ELEMENTS.
; E36E = E360 + 14: speed of the snakes

; Number of "magic elements".
; At floor 2: dragons, snakes, bursting balls, ...
; Also at floor 4, with elements thrown by the magician
; Unknown at 0xE380
NUM_MAGICAL_ELEMENTS: EQU 0xE381
TBL_MAGICAL_ELEMENTS: EQU 0xE382

MAGICAL_ELEMENT_LOOKAT_IDX: EQU 0 ; E382

; This counter controls how many ticks the falling magical element will
; stay in that state
MAGICAL_ELEMENT_STATE_IDX: EQU 1 ; E383
MAGICAL_ELEMENT_DISTANCE_L_IDX: EQU 2 ; E384
MAGICAL_ELEMENT_DISTANCE_H_IDX: EQU 3 ; E385

; Height of falling or floating magical elements
MAGICAL_ELEMENT_HEIGHT_L_IDX: EQU 4 ; E386
MAGICAL_ELEMENT_HEIGHT_H_IDX: EQU 5 ; E387

CURRENT_FRAME_IDX: EQU 6 ; E388
FRAME_COUNTER_IDX: EQU 7 ; E389

; Ticks left before the magician's fireballs turns into a bat,
; Ticks before the confetti ball explodes.
FIREBALL_TIMEOUT_IDX: EQU 8 ; 0xE38A

; (IDX 9 unused)

MAGICAL_ELEMENT_FALL_ACCELERATION_L_IDX: EQU 10 ; E38C
MAGICAL_ELEMENT_FALL_ACCELERATION_H_IDX: EQU 11 ; E38D

MAGICAL_ELEMENT_FALL_SPEED_L_IDX: EQU 12 ; E38E
MAGICAL_ELEMENT_FALL_SPEED_H_IDX: EQU 13 ; E38F


MAGICAL_ELEMENT_HOR_OFFSET_L_IDX: EQU 14; E390
MAGICAL_ELEMENT_HOR_OFFSET_H_IDX: EQU 15; E391

; This seems to control the falling height of the confetti ball
MAGICAL_ELEMENT_HEIGHT_OFFSET_L_IDX: EQU 16; E392
MAGICAL_ELEMENT_HEIGHT_OFFSET_H_IDX: EQU 17; E393

ME_INITIAL_FALL_SPEED: EQU 0xE36C
ME_INITIAL_FALL_SPEED_COPY: EQU 0xE80C

ME_STATE_POT_FALLS: EQU 0
ME_STATE_POT_TOUCHES_FLOOR: EQU 3
ME_STATE_SNAKE_WALKING: EQU 4
ME_STATE_CONFETTI_EXPLODES: EQU 5
ME_STATE_CONFETTI_FALLS_AND_FLOATS: EQU 6
ME_STATE_DRAGON_FALLS: EQU 1
ME_STATE_DRAGON_SMOKE_APPEARS: EQU 7
ME_STATE_DRAGON_OUT_AND_WILL_FIRE: EQU 8
ME_STATE_DRAGON_DISAPPEARS: EQU 9
ME_STATE_CONFETTI_MOVES_DIAGONAL: EQU 10

BOUNCING_BALL_EXPLODE_TIMEOUT_INIT: EQU 0xE371
